apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  project: default
  source:
    repoURL: https://github.com/vunguyenhung/argocd-prod-flow-demo-deployment
    # Trunk based development, so latest code is always in main branch
    targetRevision: main
    path: "."
    helm:
      valueFiles:
      - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
