apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vunguyenhung/argocd-prod-flow-demo-deployment
    # Track latest tags >= 0.0.0-0
    # 1.0.1-alpha
    # 1.0.2-release
    # 1.0.2-rc
    # 1.0.4
    # 1.0.4-prod
    # 1.0.4-uat
    targetRevision: ">=0.0.0-prod"
    path: "."
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      selfHeal: true