apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vunguyenhung/argocd-prod-flow-demo-deployment
    targetRevision: *-uat
    path: ""
    helm:
      valueFiles:
      - values-uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default