replicaCount: 1

image:
  repository: ghcr.io/vunguyenhung/demo
  tag: "0.1.0-prod"
  pullPolicy: Always
  ports:
    - name: http
      containerPort: 8080

service:
  type: ClusterIP
  port: 8080

resources: {}
