name: Update Image Tag in Values File
description: "Update the image tag in the values file if it has changed."

inputs:
  file_path:
    required: true
    type: string
  image_tag:
    required: true
    type: string
  base_branch:
    required: true
    type: string
  temp_branch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.base_branch }}

    - name: Get current version from file
      id: get_current_version
      run: |
        CURRENT_VERSION=$(grep 'tag:' ${{ inputs.file_path }} | awk '{print $2}')
        echo "Current version: $CURRENT_VERSION"
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check if image tag has changed
      id: check_image_tag
      run: |
        CURRENT_VERSION_LOWER=$(echo "${{ steps.get_current_version.outputs.current_version }}" | tr '[:upper:]' '[:lower:]')
        NEW_IMAGE_TAG_LOWER=$(echo "${{ inputs.image_tag }}" | tr '[:upper:]' '[:lower:]')
        if [ "$NEW_IMAGE_TAG_LOWER" == "$CURRENT_VERSION_LOWER" ]; then
          echo "Image tag has not changed. Exiting."
          exit 1
        else
          echo "Image tag has changed. Continuing workflow."
        fi
      shell: bash

    - name: Create a new temporary branch from base branch
      id: create_temp_branch
      run: |
        git fetch origin ${{ inputs.base_branch }}
        git checkout ${{ inputs.base_branch }}
        git checkout -b ${{ inputs.temp_branch }}
        echo "temp_branch=${{ inputs.temp_branch }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Update image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ inputs.image_tag }}/" ${{ inputs.file_path }}
        echo "Updated version to: ${{ inputs.image_tag }}"
        cat ${{ inputs.file_path }}
      shell: bash

    - name: Print GitHub objects and event for debug
      run: |
        echo "GITHUB_CONTEXT:"
        echo "${{ toJson(github) }}"
        echo "EVENT_CONTEXT:"
        cat $GITHUB_EVENT_PATH
      shell: bash

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ inputs.file_path }}
        git commit -m "${{ inputs.file_path }}: Update image tag to ${{ inputs.image_tag }}"
        git push origin ${{ inputs.temp_branch }}
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const body = {
            owner,
            repo,
            head: process.env.TEMP_BRANCH,
            base: process.env.BASE_BRANCH,
            title: `${process.env.FILE_PATH}: Update image tag to ${process.env.IMAGE_TAG}`,
            body: `New version: ${process.env.IMAGE_TAG}`
          };
          console.log(`Creating PR with the following details:`);
          console.log(JSON.stringify(body, null, 2));

          const { data: pr } = await github.rest.pulls.create(body);
          core.setOutput('pr_number', pr.number);
          core.setOutput('pr_url', pr.html_url);
      env:
        TEMP_BRANCH: ${{ inputs.temp_branch }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        FILE_PATH: ${{ inputs.file_path }}

    - name: Print PR details
      run: |
        echo "Pull Request created: ${{ steps.create_pr.outputs.pr_url }}"
      shell: bash

    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: process.env.PR_NUMBER,
            merge_method: 'squash'
          });
          await github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `heads/${process.env.TEMP_BRANCH}`
          });
      env:
        PR_NUMBER: ${{ steps.create_pr.outputs.pr_number }}
        TEMP_BRANCH: ${{ steps.create_temp_branch.outputs.temp_branch }}
